// The Sādhanā lexicon.
// Every term used in the project, with its primary-source location and the
// working definition this practice uses. The agent reads this through
// philosophy.md; the user reads it through the Lexicon view (Śabda).
//
// Schema:
//   term:       transliteration with diacritics
//   devanagari: Devanagari where the term has one
//   root:       etymology / literal sense
//   tooltip:    a single sentence for hover (≤ 120 chars)
//   working:    a paragraph — the working definition used here
//   source:     primary-source citation
//   practice:   where it shows up in this app
//   related:    cross-references to other lexicon terms

(function (global) {
  'use strict';

  const LEXICON = [
    {
      term: 'sādhanā',
      devanagari: 'साधना',
      root: 'sādh — to accomplish, to bring to completion',
      tooltip: 'Disciplined practice aimed at accomplishment of an aim.',
      working: 'A practice undertaken in earnest, over time, oriented toward a specific aim. Not a hobby; not a phase. The aim of *this* sādhanā is the stilling of the mind in Patañjali\'s sense, by way of daily structure and reflective integration.',
      source: 'Common in classical and tantric literature; cf. Patañjali 2.1 on kriyā-yoga as composed of tapas, svādhyāya, and īśvara-praṇidhāna.',
      practice: 'The name of this project. The four stages — planner, reflector, draft, research — are the form the sādhanā takes here.',
      related: ['abhyāsa', 'tapas', 'svādhyāya', 'kriyā-yoga'],
    },
    {
      term: 'smṛti',
      devanagari: 'स्मृति',
      root: 'smṛ — to remember',
      tooltip: 'Remembrance; the held thread of awareness through time.',
      working: 'Memory not as recall of facts but as continuity of awareness. In Patañjali (1.20), smṛti is one of the five aids to samādhi — the capacity to keep the thread.',
      source: 'Yoga Sūtra 1.20; also a vast Sanskrit textual category (smṛti vs. śruti).',
      practice: 'The Today view. The day held in awareness, not forgotten on the way to the next one.',
      related: ['svādhyāya', 'dhāraṇā'],
    },
    {
      term: 'prātaḥ',
      devanagari: 'प्रातः',
      root: 'pra-at — going forth; the going-forth of the day',
      tooltip: 'Early morning; the going-forth of the day.',
      working: 'The hour before the world begins. In every tradition that takes practice seriously, this is the hour reserved for it — not by accident, but because the mind is not yet defended.',
      source: 'Pervasive in Vedic and post-Vedic ritual; the morning sandhyā is observed at prātaḥ-kāla.',
      practice: 'The Morning view — wake, breathwork, run. The day\'s tone is set here or not at all.',
      related: ['tapas', 'prāṇāyāma'],
    },
    {
      term: 'tapas',
      devanagari: 'तपस्',
      root: 'tap — to heat, to burn, to glow',
      tooltip: 'Disciplined heat; the willingness to do what you resist.',
      working: 'Disciplined heat. The willingness to do what you resist. The fire that purifies by friction. Not punishment of the body, but its tempering. The aMCC is the neurological organ tapas builds and atrophies.',
      source: 'Yoga Sūtra 2.1, 2.32, 2.43 — the third of the kriyā-yoga triad and second of the niyamas. Pervasive in Ṛg Veda.',
      practice: 'The Resistance task tier. The morning anchor. The resistance score. The first metric of the practice.',
      related: ['abhyāsa', 'sādhanā', 'kriyā-yoga'],
    },
    {
      term: 'abhyāsa',
      devanagari: 'अभ्यास',
      root: 'abhi-as — to throw oneself toward; repeated effort',
      tooltip: 'Sustained practice, repeated whether or not one feels like it.',
      working: 'Patañjali names abhyāsa and vairāgya as the two instruments of nirodha. Abhyāsa is sustained, uninterrupted, undertaken with reverence over a long time (1.14). Without it, vairāgya is mere drift.',
      source: 'Yoga Sūtra 1.12–1.14.',
      practice: 'The schedule itself is abhyāsa. The streaks track its continuity, not as gamification, but as evidence of presence.',
      related: ['vairāgya', 'tapas', 'sādhanā'],
    },
    {
      term: 'vairāgya',
      devanagari: 'वैराग्य',
      root: 'vi-rāga — without coloring; absence of craving',
      tooltip: 'Non-attachment; releasing the grip on what practice will produce.',
      working: 'Not indifference. Releasing the grip on outcome. Practice without vairāgya becomes compulsion; vairāgya without practice becomes drift. The recurrence test in the nightly review is vairāgya in operational form.',
      source: 'Yoga Sūtra 1.12, 1.15–1.16.',
      practice: 'The fourth svādhyāya question. The agent\'s refusal to over-promise.',
      related: ['abhyāsa', 'amor fati', 'karma-yoga'],
    },
    {
      term: 'ekāgratā',
      devanagari: 'एकाग्रता',
      root: 'eka-agra — one-pointed',
      tooltip: 'Single-pointed attention; one object held without wavering.',
      working: 'Attention bound to a single object. The state dhāraṇā cultivates and dhyāna sustains. The deep work block is the secular form of ekāgratā: ninety minutes, one task, no other.',
      source: 'Yoga Sūtra 3.11–3.12; the contrast with vikṣipta (scattered) mind.',
      practice: 'The Deep Work tier. The single-task lock that greys out all other deep-work tasks while one is running.',
      related: ['dhāraṇā', 'dhyāna', 'samādhi'],
    },
    {
      term: 'svādhyāya',
      devanagari: 'स्वाध्याय',
      root: 'sva-adhi-i — going toward the self',
      tooltip: 'Self-study; the day reviewed without flattery.',
      working: 'Originally the recitation and study of sacred texts; in Patañjali, expanded to study of the self. The day reviewed in the evening, the patterns watched, the shadow material noticed. The text being studied is the practitioner.',
      source: 'Yoga Sūtra 2.1, 2.32, 2.44 — second member of kriyā-yoga, fourth niyama.',
      practice: 'The nightly review. Four questions, recorded with date, scrollable history. Stage 2 of the agent reads them as ground.',
      related: ['darpaṇa', 'shadow', 'individuation', 'kriyā-yoga'],
    },
    {
      term: 'īśvara-praṇidhāna',
      devanagari: 'ईश्वरप्रणिधान',
      root: 'īśvara — lord; praṇidhāna — surrender, dedication',
      tooltip: 'Surrender to what is; structurally identical to amor fati.',
      working: 'Surrender of the fruits of action to īśvara — the lord, but in the operational sense, the totality of what is. Not resignation. Active acceptance of what was, exactly as it was. Structurally identical to Nietzsche\'s amor fati.',
      source: 'Yoga Sūtra 1.23, 2.1, 2.45.',
      practice: 'The fourth svādhyāya question — the recurrence test. Would I will this day again?',
      related: ['vairāgya', 'amor fati', 'kaivalya'],
    },
    {
      term: 'kleśa',
      devanagari: 'क्लेश',
      root: 'kliś — to afflict, to torment',
      tooltip: 'Structural distortions of perception: ignorance, ego, craving, aversion, clinging.',
      working: 'The five afflictions named in Sūtra 2.3: avidyā (ignorance), asmitā (I-making), rāga (craving), dveṣa (aversion), abhiniveśa (clinging to life). Not sins — structural distortions the practitioner learns to see operating in real time.',
      source: 'Yoga Sūtra 2.3–2.9.',
      practice: 'The second and third svādhyāya questions probe rāga, dveṣa, and the asmitā that sparring exposes.',
      related: ['avidyā', 'svādhyāya', 'shadow'],
    },
    {
      term: 'avidyā',
      devanagari: 'अविद्या',
      root: 'a-vidyā — not-knowing',
      tooltip: 'Mistaking the transient for the eternal; the root kleśa.',
      working: 'The root kleśa, the field in which the other four grow (2.4). Mistaking the impermanent for the permanent, the impure for the pure, the painful for pleasant, the not-self for self. What Jung called the unconscious.',
      source: 'Yoga Sūtra 2.4–2.5.',
      practice: 'The agent\'s job is to make the unconscious incrementally conscious — to name what the user has not yet seen.',
      related: ['kleśa', 'shadow', 'individuation'],
    },
    {
      term: 'prāṇāyāma',
      devanagari: 'प्राणायाम',
      root: 'prāṇa — life-breath; āyāma — extension, restraint',
      tooltip: 'Regulation of the breath; the fourth limb.',
      working: 'The conscious lengthening, retention, and patterning of the breath. The fourth of the eight limbs. The bridge from gross body to subtle mind. Wim Hof is a modern protocol with ancient grammar.',
      source: 'Yoga Sūtra 2.49–2.53.',
      practice: 'The morning breathwork timer. Rounds, breaths, breath-hold with personal-best tracking.',
      related: ['prātaḥ', 'pratyāhāra'],
    },
    {
      term: 'pratyāhāra',
      devanagari: 'प्रत्याहार',
      root: 'prati-ā-hṛ — drawing back',
      tooltip: 'Withdrawal of the senses from their objects; the fifth limb.',
      working: 'The senses turning back from their objects, the way a tortoise withdraws its limbs (the Gītā\'s image, 2.58). Not sensory deprivation — a re-orientation of attention from outward to inward.',
      source: 'Yoga Sūtra 2.54–2.55; Bhagavad Gītā 2.58.',
      practice: 'The Sunday active recovery, the wind-down hour, the discipline of closing the laptop.',
      related: ['prāṇāyāma', 'dhāraṇā'],
    },
    {
      term: 'dhāraṇā',
      devanagari: 'धारणा',
      root: 'dhṛ — to hold',
      tooltip: 'Concentration: attention bound to one place.',
      working: 'Attention bound to one place (3.1). The capacity to hold a single object before the mind. The sixth limb. Where ekāgratā becomes practicable.',
      source: 'Yoga Sūtra 3.1.',
      practice: 'The deep work block trains dhāraṇā at human scale: 90 minutes, one task.',
      related: ['ekāgratā', 'dhyāna'],
    },
    {
      term: 'dhyāna',
      devanagari: 'ध्यान',
      root: 'dhyai — to contemplate',
      tooltip: 'Sustained attention; the unbroken flow.',
      working: 'The unbroken flow of attention toward the object dhāraṇā has bound (3.2). The seventh limb. The deep work block lived all the way through is dhyāna.',
      source: 'Yoga Sūtra 3.2.',
      practice: 'The state inside a sustained deep work block when the timer is forgotten.',
      related: ['dhāraṇā', 'samādhi', 'ekāgratā'],
    },
    {
      term: 'samādhi',
      devanagari: 'समाधि',
      root: 'sam-ā-dhā — placing together, putting in',
      tooltip: 'Absorption: attender and attended become indistinguishable.',
      working: 'The state in which the act of attending and the object attended become indistinguishable (3.3). The eighth limb. Not a mystical reward — a phenomenological description of complete attention.',
      source: 'Yoga Sūtra 3.3; the entirety of pāda 1 is on samādhi.',
      practice: 'Rare and not engineered. Sometimes occurs in sparring, in deep work, in the breath-hold.',
      related: ['dhyāna', 'kaivalya'],
    },
    {
      term: 'kaivalya',
      devanagari: 'कैवल्य',
      root: 'kevala — alone, isolated',
      tooltip: 'Recognition that the witness was never bound by what it witnessed.',
      working: 'The "goal" of Patañjali\'s system (4.34), but not attainment of a state — recognition that the witness was never bound by what it witnessed. The practice does not produce kaivalya; it removes what obscures it.',
      source: 'Yoga Sūtra 4.34.',
      practice: 'Not a metric. The frame within which all the metrics are held.',
      related: ['samādhi', 'witness', 'advaita'],
    },
    {
      term: 'kriyā-yoga',
      devanagari: 'क्रियायोग',
      root: 'kriyā — action; yoga — union',
      tooltip: 'The yoga of action: tapas, svādhyāya, īśvara-praṇidhāna.',
      working: 'Patañjali\'s practical triad (2.1): tapas, svādhyāya, īśvara-praṇidhāna. The yoga that can be done in the middle of life, by people who have not renounced it. This is the project\'s skeletal structure.',
      source: 'Yoga Sūtra 2.1.',
      practice: 'Tapas → morning anchor and resistance tasks. Svādhyāya → review. Īśvara-praṇidhāna → recurrence test. All three, every day.',
      related: ['tapas', 'svādhyāya', 'īśvara-praṇidhāna'],
    },
    {
      term: 'yuddha',
      devanagari: 'युद्ध',
      root: 'yudh — to fight',
      tooltip: 'Battle; here, boxing as the integration vessel.',
      working: 'Battle. The condition of the Gītā\'s opening. The arena where every other limb of the practice is tested at once. Boxing is yuddha because it makes ekāgratā, tapas, svādhyāya, and the witness non-optional.',
      source: 'Bhagavad Gītā 1; pervasive across Mahābhārata.',
      practice: 'The Boxing view. Round timer, session log, weekly template, sparring shadow log.',
      related: ['svadharma', 'tapas', 'witness'],
    },
    {
      term: 'svadharma',
      devanagari: 'स्वधर्म',
      root: 'sva-dharma — one\'s own dharma',
      tooltip: 'One\'s own specific duty, arising from one\'s own specific nature.',
      working: 'Your specific duty, arising from your specific nature. Krishna tells Arjuna that the inferior svadharma performed is better than another\'s performed well (3.35). The antidote to the modern fantasy of being elsewhere.',
      source: 'Bhagavad Gītā 2.31, 3.35, 18.47.',
      practice: 'The weekly template is svadharma made concrete — what *this* practitioner trains, not a generic regime.',
      related: ['karma-yoga', 'yuddha'],
    },
    {
      term: 'karma-yoga',
      devanagari: 'कर्मयोग',
      root: 'karma — action; yoga — union',
      tooltip: 'Action performed without grip on the fruit.',
      working: 'Action performed without grasping the fruit. Gītā 2.47 in operational form: the right is to the action, not to its outcome. Compatible with full intensity of effort, incompatible with anxiety about result.',
      source: 'Bhagavad Gītā 2.47–2.51, 3.1–3.30.',
      practice: 'The estimated-vs-actual minute tracking is karma-yoga in miniature: you commit to the effort, you record what actually happened, you do not own the gap.',
      related: ['vairāgya', 'svadharma', 'amor fati'],
    },
    {
      term: 'guṇa',
      devanagari: 'गुण',
      root: 'guṇa — strand, quality',
      tooltip: 'Sattva (clarity), rajas (drive), tamas (inertia).',
      working: 'The three strands woven through all experience. Sattva is luminosity, rajas is drive, tamas is inertia. The practitioner notices which dominates and adjusts. The resistance score is a guṇa probe: did you push through tamas, or did it close on you?',
      source: 'Bhagavad Gītā 14; Sāṃkhya tradition.',
      practice: 'The metrics are largely a guṇa map. Tamas mornings, rajas afternoons, sattva evenings — or the inverse, which is itself diagnostic.',
      related: ['tapas', 'sattva', 'rajas', 'tamas'],
    },
    {
      term: 'darpaṇa',
      devanagari: 'दर्पण',
      root: 'darpaṇa — mirror',
      tooltip: 'The mirror; the agent as svādhyāya\'s reflector.',
      working: 'The mirror. The agent\'s role: to reflect what the day held, without flattery. The mirror does not produce the face; it shows it. The agent does not produce the practice; it shows what the practice has been.',
      source: 'Common Sanskrit term; image of the mind-as-mirror in Vedānta.',
      practice: 'Stage 2 — the reflector at agent.html. Reads svādhyāya, returns one specific question for tomorrow.',
      related: ['svādhyāya', 'witness'],
    },
    {
      term: 'manana',
      devanagari: 'मनन',
      root: 'man — to think; manana — sustained contemplation',
      tooltip: 'Contemplation; sustained reflection on a teaching.',
      working: 'The second of Vedānta\'s three reflective steps: śravaṇa (hearing the teaching), manana (sustained reflection on it), nididhyāsana (steady meditation). The middle stage where the teaching is turned over until it ceases to be other than oneself.',
      source: 'Bṛhadāraṇyaka Upaniṣad 2.4.5; pervasive in Vedānta commentaries.',
      practice: 'The Contemplation view — quotes treated as objects of manana, not decoration.',
      related: ['svādhyāya', 'śabda'],
    },
    {
      term: 'śabda',
      devanagari: 'शब्द',
      root: 'śabda — sound, word',
      tooltip: 'Word/sound; in this app, the lexicon you are reading.',
      working: 'Word as bearer of meaning. In Mīmāṃsā and Vedānta epistemology, śabda is a means of valid knowledge — what is reliably transmitted by word. The lexicon is śabda made visible: terms with their sources, so the words do not float free of their meaning.',
      source: 'Mīmāṃsā Sūtra; classical pramāṇa-vāda discussions.',
      practice: 'The Lexicon view itself.',
      related: ['manana', 'svādhyāya'],
    },
    {
      term: 'kāla',
      devanagari: 'काल',
      root: 'kāla — time, the dark one',
      tooltip: 'Time; also the devourer.',
      working: 'Time. Also a name of what consumes. The Gītā\'s most famous and most terrifying verse — *kālo \'smi loka-kṣaya-kṛt* (11.32), "I am time, the destroyer of worlds" — names time as the field of all action and the end of all action. The schedule is kāla made local.',
      source: 'Bhagavad Gītā 11.32; widely in Sanskrit cosmology.',
      practice: 'The Schedule view. Time blocked, edited, kept, lost.',
      related: ['abhyāsa', 'svadharma'],
    },
    {
      term: 'saṃkhyā',
      devanagari: 'संख्या',
      root: 'sam-khyā — counting, enumeration',
      tooltip: 'Number, measure; the metrics view.',
      working: 'Counting, enumeration. Related to Sāṃkhya, the philosophical school that enumerates the constituents of experience. Measurement as a practice of clarity, not of optimization.',
      source: 'Common Sanskrit; cf. the Sāṃkhya darśana.',
      practice: 'The Metrics view. Streaks, charts, monthly compound. Data as svādhyāya at scale.',
      related: ['svādhyāya', 'guṇa'],
    },
    {
      term: 'vidhi',
      devanagari: 'विधि',
      root: 'vi-dhā — to ordain, to lay down',
      tooltip: 'Rule, ordinance; configuration.',
      working: 'Rule, ordinance, what has been laid down. In ritual contexts, the prescribed procedure. Settings is vidhi — the rules under which the practice operates this season.',
      source: 'Pervasive in dharmaśāstra and Mīmāṃsā.',
      practice: 'The Settings view. The 14-day rule itself is the most important vidhi.',
      related: ['svadharma'],
    },
    {
      term: 'witness',
      devanagari: 'साक्षिन्',
      root: 'sākṣin — eye-witness, observer',
      tooltip: 'The observer behind the doing; structurally non-separate from what it observes.',
      working: 'The observer behind the doing. In Vedānta, the sākṣin is the consciousness that knows the changing states without itself changing. Boxing makes the witness literal: the fighter who watches himself fight does not fight worse.',
      source: 'Upaniṣads, Vedānta commentaries; Patañjali 4.18–4.20.',
      practice: 'Implicit in every reflective question. The agent is a second-order witness — the witness that watches the witnessing.',
      related: ['kaivalya', 'advaita', 'svādhyāya'],
    },
    {
      term: 'advaita',
      devanagari: 'अद्वैत',
      root: 'a-dvaita — not-two',
      tooltip: 'Non-duality; observer and observed are not separable.',
      working: 'Not-two. The recognition that observer and observed are structurally non-separate. The double-slit experiment in modern physics is the cleanest empirical pointer toward this — the electron behaves differently when measured.',
      source: 'Upaniṣads; Śaṅkara\'s commentaries.',
      practice: 'The frame, not an item. The reason svādhyāya works at all.',
      related: ['witness', 'kaivalya'],
    },
    {
      term: 'amor fati',
      devanagari: '',
      root: 'Latin: amor — love; fati — of fate',
      tooltip: 'Love of fate. Active acceptance, not resignation.',
      working: 'Nietzsche\'s name for what Patañjali was pointing at with īśvara-praṇidhāna. Active love of what is, not passive resignation. The eternal recurrence is the test: would you will this exact life, eternally, exactly as it is?',
      source: 'Nietzsche, *The Gay Science* §276; *Ecce Homo* II.10.',
      practice: 'The fourth svādhyāya question. Y/N + one sentence.',
      related: ['īśvara-praṇidhāna', 'vairāgya'],
    },
    {
      term: 'shadow',
      devanagari: '',
      root: 'Jung\'s Schatten — what the conscious personality has not integrated',
      tooltip: 'Everything the conscious personality has refused to host.',
      working: 'Everything the conscious personality has refused to host. Not evil — disowned capacity. The reaction disproportionate to its trigger is the shadow projecting. Sparring is the most direct shadow tool the practice contains.',
      source: 'C.G. Jung, *Aion* (1951), CW 9ii; *The Archetypes and the Collective Unconscious*, CW 9i.',
      practice: 'The second svādhyāya question. The "what got exposed" field in sparring.',
      related: ['individuation', 'avidyā', 'svādhyāya'],
    },
    {
      term: 'individuation',
      devanagari: '',
      root: 'Jung — the lifelong work of integrating the disowned',
      tooltip: 'The lifelong work of integrating what one has disowned.',
      working: 'Jung\'s name for the process by which the disowned material is digested and made part of the conscious personality. Not a goal achievable in a year, or ten. The arc the practice serves.',
      source: 'C.G. Jung, *Memories, Dreams, Reflections*; *Two Essays on Analytical Psychology*, CW 7.',
      practice: 'The trailing 30-day shadow review the agent performs. Recurrence of unintegrated material is the signal.',
      related: ['shadow', 'svādhyāya', 'kaivalya'],
    },
    {
      term: 'saṅkalpa',
      devanagari: 'सङ्कल्प',
      root: 'sam-kḷp — to put together, to form, to resolve',
      tooltip: 'Resolve, intention; the seed of manifestation in yogic understanding.',
      working: 'The seed of intention. In Yoga Nidrā, the saṅkalpa is repeated three times at the start and end of the practice — a single sentence in the present tense, planted in the receptive mind. The pre-modern name for what Proctor calls paradigm-shift through repetition and Dispenza calls mental rehearsal of the future self. The Gītā warns against desires born of saṅkalpa (6.24); the practice refines saṅkalpa until it is aligned with svadharma.',
      source: 'Bṛhadāraṇyaka Upaniṣad 4.4.5; Bhagavad Gītā 6.24; central in Yoga Nidrā tradition (Satyananda).',
      practice: 'The Saṅkalpa view. The orchestra is a garland of nine saṅkalpas built over nine months.',
      related: ['mantra', 'japa', 'bhāvanā', 'vāsanā'],
    },
    {
      term: 'mantra',
      devanagari: 'मन्त्र',
      root: 'man — to think; tra — instrument; "mind-instrument" or "that which protects the mind in repetition"',
      tooltip: 'A phrase repeated until it shapes the mind that repeats it.',
      working: 'A phrase, syllable, or sentence used as the instrument of attention. Mantra works because the mind takes the shape of what it repeatedly holds. Patañjali 1.27–28 names the praṇava (Om) as īśvara\'s expression and prescribes its repetition with reflection on meaning.',
      source: 'Patañjali 1.27–1.28; pervasive in Vedic, tantric, and bhakti traditions.',
      practice: 'The mantra panel in the Saṅkalpa view. Assembled from active orchestra affirmations.',
      related: ['saṅkalpa', 'japa', 'praṇava'],
    },
    {
      term: 'japa',
      devanagari: 'जप',
      root: 'jap — to mutter, to repeat',
      tooltip: 'Repetition of a mantra, with reflection on its meaning.',
      working: 'The repetition of a mantra. Patañjali 1.28: *taj-japas tad-artha-bhāvanam* — "its repetition with reflection on its meaning." Counted traditionally on a mālā of 108 beads; the count is not the point, the un-distracted holding is.',
      source: 'Yoga Sūtra 1.28; foundational across yogic and bhakti practice.',
      practice: 'The japa counter in the Saṅkalpa view. +1 and +108 buttons.',
      related: ['mantra', 'saṅkalpa', 'bhāvanā'],
    },
    {
      term: 'bhāvanā',
      devanagari: 'भावना',
      root: 'bhū — to be, to become; bhāvanā — the act of bringing into being',
      tooltip: 'Cultivation; sustained holding of a quality until it becomes one\'s state.',
      working: 'Cultivation. Bringing-into-being through sustained attention. What Dispenza calls mental rehearsal, the yogis called bhāvanā — the holding of a feeling-tone until the body and mind take its shape. Patañjali 1.28 uses bhāvanā as the modifier of japa.',
      source: 'Yoga Sūtra 1.28, 2.33–2.34 (pratipakṣa-bhāvanā — cultivation of the opposite).',
      practice: 'The orchestra movements are bhāvanās — each month cultivates one quality until it has become ground for the next.',
      related: ['japa', 'mantra', 'abhyāsa'],
    },
    {
      term: 'viparyaya',
      devanagari: 'विपर्यय',
      root: 'vi-pari-i — to go astray, to invert',
      tooltip: 'Wrong cognition; taking the unreal as real.',
      working: 'False knowledge, the second of the five vṛttis (1.6, 1.8). Patañjali defines it as *mithyā-jñānam atad-rūpa-pratiṣṭham* — false knowledge that does not rest on the form of its object. The limiting belief that is contradicted by reality once examined. The wrong-thought log defuses viparyaya by naming it.',
      source: 'Yoga Sūtra 1.8.',
      practice: 'The Wrong Thought (mithyā-jñāna) panel in the Saṅkalpa view.',
      related: ['kleśa', 'avidyā', 'svādhyāya'],
    },
    {
      term: 'vāsanā',
      devanagari: 'वासना',
      root: 'vas — to dwell; vāsanā — what dwells in the mind',
      tooltip: 'Latent impressions that shape future tendencies; the paradigm.',
      working: 'The residue of past actions that conditions future inclinations. The "paradigm" in Bob Proctor\'s vocabulary — the subconscious pattern that produces a life. Saṃskāras are the discrete impressions; vāsanās are the resulting dispositional pull.',
      source: 'Yoga Sūtra 4.8–4.11; Vedānta literature.',
      practice: 'What the orchestra reshapes. The nine-month arc is vāsanā-cultivation by design.',
      related: ['saṃskāra', 'kleśa', 'bhāvanā'],
    },
    {
      term: 'saṃskāra',
      devanagari: 'संस्कार',
      root: 'sam-kṛ — to put together, to construct, to refine',
      tooltip: 'Mental impression; the discrete trace each act leaves.',
      working: 'The trace each thought, word, and deed leaves in the mind. Saṃskāras accumulate into vāsanās. The aMCC enlarges through repeated acts of doing what one resists — that enlargement is saṃskāra made visible in tissue.',
      source: 'Yoga Sūtra 1.18, 1.50, 2.15, 3.9, 3.18; pervasive in Buddhist Abhidharma as well.',
      practice: 'Every recorded day deposits saṃskāra. The metrics dashboard visualizes their accumulation.',
      related: ['vāsanā', 'abhyāsa', 'tapas'],
    },
    {
      term: 'nididhyāsana',
      devanagari: 'निदिध्यासन',
      root: 'ni-dhyai — sustained meditation',
      tooltip: 'The third of Vedānta\'s reflective steps: steady meditation on what has been understood.',
      working: 'After śravaṇa (hearing) and manana (sustained reflection), nididhyāsana is the steady meditation that lets the teaching cease to be other than oneself. The five-whys practice is one form: each "why" is a manana cut, repeated until the chain bottoms out in something irreducible.',
      source: 'Bṛhadāraṇyaka Upaniṣad 2.4.5; Vivekacūḍāmaṇi 365; Vedānta pedagogy generally.',
      practice: 'The Five Whys panel in the Saṅkalpa view.',
      related: ['manana', 'svādhyāya', 'dhyāna'],
    },
    {
      term: 'abhaya',
      devanagari: 'अभय',
      root: 'a-bhaya — non-fear; freedom from fear',
      tooltip: 'Fearlessness; the first quality in the Gītā\'s catalogue of the divine.',
      working: 'Fearlessness. Not the absence of fear, but the disposition that proceeds anyway. The Gītā\'s catalogue of divine qualities (16.1) opens with abhayam — fearlessness is named first. Month 1 of the orchestra cultivates it by embracing bhaya rather than fleeing it.',
      source: 'Bhagavad Gītā 16.1; the abhaya-mudrā gesture across Hindu and Buddhist iconography.',
      practice: 'Orchestra movement 1.',
      related: ['kleśa', 'shadow', 'tapas'],
    },
    {
      term: 'jijñāsā',
      devanagari: 'जिज्ञासा',
      root: 'jñā — to know; jijñāsā — desire to know (desiderative form)',
      tooltip: 'The desire to know; the natural orientation once fear loosens.',
      working: 'The desire to know. The Brahma Sūtras open with *athāto brahma-jijñāsā* — "now therefore, the inquiry into brahman." Curiosity is what fills the space fear vacates.',
      source: 'Brahma Sūtra 1.1.1.',
      practice: 'Orchestra movement 2.',
      related: ['svādhyāya', 'manana'],
    },
    {
      term: 'dhṛti',
      devanagari: 'धृति',
      root: 'dhṛ — to hold',
      tooltip: 'Determination; the holding-firm that sustains practice.',
      working: 'The holding-firm. Gītā 18.33–35 distinguishes three modes of dhṛti by guṇa: the sāttvic form is sustained will toward what is true; the rājasic clings to fruit; the tāmasic clings to fear and grief.',
      source: 'Bhagavad Gītā 18.33–18.35.',
      practice: 'Orchestra movement 5.',
      related: ['vīrya', 'abhyāsa', 'tapas'],
    },
    {
      term: 'pratibhā',
      devanagari: 'प्रतिभा',
      root: 'prati-bhā — to shine forth toward',
      tooltip: 'Creative insight; knowledge that is seen, not deduced.',
      working: 'The flash of creative insight. Patañjali 3.33 says it arises when discrimination matures — knowledge that is not deduced but seen. The artistic capacity is its earthly form; the same word names both poetic inspiration and yogic intuition.',
      source: 'Yoga Sūtra 3.33; Sanskrit aesthetic theory (Abhinavagupta).',
      practice: 'Orchestra movement 6.',
      related: ['dhyāna', 'jijñāsā'],
    },
    {
      term: 'vīrya',
      devanagari: 'वीर्य',
      root: 'vīra — hero; vīrya — heroic energy',
      tooltip: 'Energy, courage, virile force; second of the five aids to samādhi.',
      working: 'Energy, courage, virile force. The second of the five aids to samādhi in Patañjali 1.20 — after śraddhā (faith) and before smṛti, samādhi, prajñā. Distinct from raw strength: vīrya is the courage that keeps moving when strength has failed.',
      source: 'Yoga Sūtra 1.20; pervasive across yogic and Buddhist (Pali: viriya) traditions.',
      practice: 'Orchestra movement 7. Also: every morning anchor honored is vīrya.',
      related: ['tapas', 'dhṛti', 'śakti'],
    },
    {
      term: 'śakti',
      devanagari: 'शक्ति',
      root: 'śak — to be able',
      tooltip: 'Power, capacity, the active principle.',
      working: 'Power, capacity, the active principle. Where vīrya is the willingness to act, śakti is the capacity to act. In tantric framing, the energetic counterpart of consciousness itself.',
      source: 'Pervasive in tantric and Śākta literature; cf. Devī Māhātmya.',
      practice: 'Orchestra movement 8 — where the inward cultivation becomes outwardly visible.',
      related: ['vīrya', 'guṇa'],
    },
    {
      term: 'sattva',
      devanagari: 'सत्त्व',
      root: 'sat — being, being-true; sattva — being-ness, luminosity',
      tooltip: 'Luminosity, clarity, balance; the guṇa in which discrimination is possible.',
      working: 'The first of the three guṇas — luminosity, clarity, balance. Not preferred in a moral sense, but the only state in which discrimination is possible. The orchestra\'s ninth month is sattva paired with prajñā — not a new instrument added, but the harmonic sounding of all eight before it.',
      source: 'Bhagavad Gītā 14.6, 14.11; Sāṃkhya tradition.',
      practice: 'Orchestra movement 9. The integration.',
      related: ['guṇa', 'prajñā', 'kaivalya'],
    },
    {
      term: 'prajñā',
      devanagari: 'प्रज्ञा',
      root: 'pra-jñā — knowing-forth, intuitive wisdom',
      tooltip: 'Wisdom; the fifth and final aid to samādhi.',
      working: 'Wisdom — not information, but the seeing that is the fruit of sustained attention. The fifth and final aid to samādhi in Patañjali 1.20. Distinct from cleverness: prajñā is the discrimination that knows the witness from the witnessed.',
      source: 'Yoga Sūtra 1.20, 1.48, 1.49; Upaniṣads; Buddhist paññā.',
      practice: 'The orchestra\'s aim — what the nine months together produce.',
      related: ['sattva', 'samādhi', 'kaivalya', 'witness'],
    },
    {
      term: 'aMCC',
      devanagari: '',
      root: 'anterior mid-cingulate cortex',
      tooltip: 'Brain region that enlarges in those who do what they resist; atrophies in those who do not.',
      working: 'A region of the brain implicated in motivation, error-monitoring, and the willingness to engage with effortful tasks. Enlarges in people who routinely do what they do not want to do; atrophies in those who only do what is easy. The neurological substrate of tapas.',
      source: 'Touroutoglou et al. 2020; Apps et al. 2016 on cingulate cost-benefit computation; Huberman lab summaries.',
      practice: 'The resistance score is the metric that crosses the ancient and the empirical.',
      related: ['tapas', 'abhyāsa'],
    },
  ];

  function find(term) {
    const lower = term.toLowerCase();
    return LEXICON.find(e => e.term.toLowerCase() === lower);
  }
  function tooltipFor(term) {
    const e = find(term);
    return e ? e.tooltip : '';
  }

  global.SadhanaLexicon = { LEXICON, find, tooltipFor };
})(typeof window !== 'undefined' ? window : globalThis);
